language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
branches:
  except:
    - test
  only:
    - main
script:
  - npm test -- --clearCache
  - npm test -- --coverage
  - CI=false npm run build
after_script:
  - COVERALLS_REPO_TOKEN=$COVERALL_TOKEN npm run coveralls
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
